<div id="controls">
    <div id="up" class="button" />
    <div id="down" class="button" />
    <div id="left" class="button" />
    <div id="right" class="button" />
    <div id="cen" class="button" />
</div>
<p>Controller!</p>

<style>
    #controls {
        position: relative;
        width: 100vw; /* Very landscape hostile */
        height: auto;
        aspect-ratio: 1/1;
        box-sizing: border-box;
        border: 1rem solid transparent;
    }
    
    /* Generated by rc_clip_paths.py */
    #up    { clip-path: polygon(34% 4%, 50% 0%, 66% 4%, 66% 32%, 60% 38%, 40% 38%, 34% 32%); }
    #left  { clip-path: polygon(4% 66%, 0% 50%, 4% 34%, 32% 34%, 38% 40%, 38% 60%, 32% 66%); }
    #down  { clip-path: polygon(66% 96%, 50% 100%, 34% 96%, 34% 68%, 40% 62%, 60% 62%, 66% 68%); }
    #right { clip-path: polygon(96% 34%, 100% 50%, 96% 66%, 68% 66%, 62% 60%, 62% 40%, 68% 34%); }
    #cen   { clip-path: polygon(40.8% 40.8%, 59.2% 40.8%, 59.2% 59.2%, 40.8% 59.2%); }

    .button {
        position: absolute;
        width: 100%;
        height: 100%;
        background-color: white;
        transition: background-color ease 0.2s;
    }

    .button:hover {
        background-color: gray;
    }
</style>