# lol manual spacing
DIRS = ['up   ', 'left ', 'down ', 'right']

# Rotate a point CCW
def rotp(p):
    (x, y) = p
    return (y, 100 - x)

# Rotate many points CCW
def rot(ps):
    return [rotp(p) for p in ps]

def print_btn(name, btn):
    path = ', '.join(f'{x}% {y}%' for (x, y) in btn)
    print(f'    #{name} {{ clip-path: polygon({path}); }}')

b =  2; # Button-button buffer width
w = 32; # Outside width
p =  4; # Pointedness
h = 12; # Half of the center width

# Directional buttons, starting with up
btn = [
    (w+b, p),
    (50, 0),
    (100-w-b, p),
    (100-w-b, w),
    (50+h-b, 50-h),
    (50-h+b, 50-h),
    (w+b, w),
]
# Center button
cen = [
    # ~sqrt(2) border so that the diagonal spacing is still b
    (50-h+1.4*b, 50-h+1.4*b),
    (50+h-1.4*b, 50-h+1.4*b),
    (50+h-1.4*b, 50+h-1.4*b),
    (50-h+1.4*b, 50+h-1.4*b)
]

print('    /* Generated by rc_clip_paths.py */')
for dir in DIRS:
    print_btn(dir, btn)
    btn = rot(btn)
print_btn('enter', cen)